import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import SignalRProvider from "./providers/SignalRProvider";
import ToasterProvider from "./providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Car Auction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className="container max-auto px-5 pt-10">
          <SignalRProvider>{children}</SignalRProvider>
        </main>
      </body>
    </html>
  );
}
